
Usage: make options...

Option            Description
------            -----------
clean             Clean build directories of projects
build             Build projects with tests and quality checking
build-fast        Build projects without tests and quality checking
release           Release a new version for projects
publish-snapshot  Publish snapshot version to Maven central
publish           Publish release version to Maven central

