# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 17
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build project with Gradle
      run: ./gradlew build publishToMavenLocal
    - name: Build examples with Gradle
      run: cd ./examples/basic-gwt-project && ./gradlew build 
        && cd ../gradle-jvm-test-suites-with-gwt && ./gradlew build
        && cd ../basic-gwt-rpc && ./gradlew build
